language: php

dist: trusty

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
#    - php: 5.6
#      env:
#        - DB=MYSQL
#    - php: 7.0
#      env:
#        - DB=PGSQL
    - php: 7.1
      env:
        - DB=MYSQL
        - PDO=1
        - PHPUNIT_TEST=1


before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:1.0.x-dev
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.0.x-dev; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - ls -l
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi