---
Name: multisitesmodelascontrollerroutes
After: 
  - modelascontrollerroutes
---
SilverStripe\Control\Director:
  rules:
    '': Symbiote\Multisites\Control\MultisitesRootController
    robots.txt: Symbiote\Multisites\Control\RobotsTxtController
    $URLSegment//$Action/$ID/$OtherID: Symbiote\Multisites\Control\MultisitesFrontController
